const endpoints = {
  dashboard: {
    read: "/dashboard/read",
  },
  auth: {
    login: "/auth/login",
    validateEmail: "/auth/validateEmail",
    generatePassword: "/auth/generatePassword",
    register: "/auth/register",
    verifyToken: "/auth/verifyToken",
    verifyTokenGeneratePassword: "/auth/verifyTokenGeneratePassword",
    verifyUser: "/auth/verifyUser",
    verifyRecoverCode: "/auth/verifyRecoverCode",
    recover: "/auth/recover",
    password: "/auth/password",
  },
  import: {
    table: "/import/table",
    project: "/import/project",
    account: "/import/account",
  },
  logs: {
    read: "/logs/read",
    readByParams: "/logs/readByParams",
    create: "/logs/create",
  },
  inbox: {
    read: "/inbox/read",
    readByUser: "/inbox/readByUser",
    readBySupport: "/inbox/readBySupport",
    readByThread: "/inbox/readByThread",
    responsible: "/inbox/responsible",
    create: "/inbox/create",
    update: "/inbox/update",
    delete: "/inbox/delete",
    close: "/inbox/close",
  },
  user: {
    read: "/user/read",
    readById: "/user/readById",
    readByEmail: "/user/readByEmail",
    update: "/user/update",
    changeStatus: "/user/changeStatus",
    create: "/user/create",
    delete: "/user/delete",
    generatePassword: "/user/generatePassword",
  },
  role: {
    read: "/role/read",
    update: "/role/update",
    create: "/role/create",
    delete: "/role/delete",
  },
  course: {
    read: "/course/read",
    readByLang: "/course/readByLang",
    readById: "/course/readById",
    readBySlug: "/course/readBySlug",
    readByTopicId: "/course/readByTopicId",
    readByTestId: "/course/readByTestId",
    report: "/course/report",
    update: "/course/update",
    updateTopic: "/course/updateTopic",
    updateProgress: "/course/updateProgress",
    resetProgress: "/course/resetProgress",
    module: "/course/module",
    create: "/course/create",
    delete: "/course/delete",
    deleteTry: "/course/deleteTry",
    duplicate: "/course/duplicate",
  },
  test: {
    update: "/course/updateTest",
  },
  email: {
    read: "/email/read",
    readById: "/email/readById",
    readByLang: "/email/readByLang",
    update: "/email/update",
    create: "/email/create",
    delete: "/email/delete",
  },
  course_certificate: {
    read: "/certificate/read",
    readById: "/certificate/readById",
    update: "/certificate/update",
    create: "/certificate/create",
    delete: "/certificate/delete",
  },
  language: {
    read: "/language/read",
    update: "/language/update",
    create: "/language/create",
    delete: "/language/delete",
    default: "/language/default",
  },
  settings: {
    read: "/settings/read",
    update: "/settings/update",
    create: "/settings/create",
    delete: "/settings/delete",
  },
  media: {
    read: "/media/read",
    upload: "/media/upload",
    singleUpload: "/media/singleUpload",
    update: "/media/update",
    delete: "/media/delete",
  },
  notification: {
    read: "/notification/read",
    readByUser: "/notification/readByUser",
    readByLang: "/notification/readByLang",
    update: "/notification/update",
    markAsRead: "/notification/markAsRead",
    create: "/notification/create",
    send: "/notification/send",
    delete: "/notification/delete",
  },
  document: {
    read: "/document/read",
    readByLang: "/document/readByLang",
    readBySlug: "/document/readBySlug",
    update: "/document/update",
    create: "/document/create",
    delete: "/document/delete",
  },
  download: {
    read: "/download/read",
    readById: "/download/readById",
    readByLang: "/download/readByLang",
    readBySlug: "/download/readBySlug",
    update: "/download/update",
    create: "/download/create",
    delete: "/download/delete",
  },
};

export default endpoints;
