const endpoints = {
	dashboard: {
		read: "/dashboard/read",
	},
	auth: {
		login: "/auth/login",
		validateEmail: "/auth/validateEmail",
		register: "/auth/register",
		verifyToken: "/auth/verifyToken",
		verifyTokenGeneratePassword: "/auth/verifyTokenGeneratePassword",
		verifyUser: "/auth/verifyUser",
		verifyRecoverCode: "/auth/verifyRecoverCode",
		recover: "/auth/recover",
		password: "/auth/password",
	},
	import: {
		table: "/import/table",
		project: "/import/project",
		account: "/import/account",
	},
	logs: {
		read: "/logs/read",
		readByParams: "/logs/readByParams",
		create: "/logs/create",
	},
	ticket: {
		read: "/ticket/read",
		readByUserId: "/ticket/readByUserId",
		readById: "/ticket/readById",
		unreadCount: "/ticket/unreadCount",
		attachment: (idTicket, name) => `/ticket/attachment/${idTicket}/${encodeURIComponent(name)}`,
		create: "/ticket/create",
		reply: "/ticket/reply",
		updateStatus: "/ticket/updateStatus",
		assignableUsers: "/ticket/assignableUsers",
		assign: "/ticket/assign",
		updatePriority: "/ticket/updatePriority",
	},
	user: {
		read: "/user/read",
		readById: "/user/readById",
		readByEmail: "/user/readByEmail",
		update: "/user/update",
		changeStatus: "/user/changeStatus",
		create: "/user/create",
		delete: "/user/delete",
	},
	permission: {
		read: "/permission/read",
		set: "/permission/set",
	},
	role: {
		read: "/role/read",
		update: "/role/update",
		create: "/role/create",
		delete: "/role/delete",
	},
	course: {
		accessUsers: "/course/accessUsers",
		setAccessUsers: "/course/setAccessUsers",
		accessGroups: "/course/accessGroups",
		setAccessGroups: "/course/setAccessGroups",
		read: "/course/read",
		readByLang: "/course/readByLang",
		readById: "/course/readById",
		readBySlug: "/course/readBySlug",
		readByTopicId: "/course/readByTopicId",
		readByTestId: "/course/readByTestId",
		report: "/course/report",
		update: "/course/update",
		updateTopic: "/course/updateTopic",
		updateProgress: "/course/updateProgress",
		resetProgress: "/course/resetProgress",
		module: "/course/module",
		create: "/course/create",
		delete: "/course/delete",
		deleteTry: "/course/deleteTry",
		duplicate: "/course/duplicate",
	},
	product: {
		read: "/product/read",
		update: "/product/update",
		create: "/product/create",
		delete: "/product/delete",
	},
	test: {
		update: "/course/updateTest",
	},
	email: {
		read: "/email/read",
		readById: "/email/readById",
		readByLang: "/email/readByLang",
		update: "/email/update",
		create: "/email/create",
		delete: "/email/delete",
		test: "/email/test",
	},
	course_certificate: {
		read: "/certificate/read",
		readById: "/certificate/readById",
		preview: "/certificate/preview",
		generate: "/certificate/generate",
		update: "/certificate/update",
		create: "/certificate/create",
		delete: "/certificate/delete",
	},
	language: {
		read: "/language/read",
		update: "/language/update",
		create: "/language/create",
		delete: "/language/delete",
		default: "/language/default",
	},
	settings: {
		read: "/settings/read",
		update: "/settings/update",
		create: "/settings/create",
		delete: "/settings/delete",
	},
	media: {
		read: "/media/read",
		upload: "/media/upload",
		singleUpload: "/media/singleUpload",
		update: "/media/update",
		delete: "/media/delete",
	},
	userGroup: {
		read: "/usergroup/read",
		create: "/usergroup/create",
		update: "/usergroup/update",
		delete: "/usergroup/delete",
		members: "/usergroup/members",
		setMembers: "/usergroup/setMembers",
	},
	iec: {
		read: "/iec/read",
		check: "/iec/check",
		upload: "/iec/upload",
		file: "/iec/file",
		delete: "/iec/delete",
	},
	notification: {
		read: "/notification/read",
		readByUser: "/notification/readByUser",
		readByLang: "/notification/readByLang",
		update: "/notification/update",
		markAsRead: "/notification/markAsRead",
		create: "/notification/create",
		send: "/notification/send",
		delete: "/notification/delete",
	},
	document: {
		read: "/document/read",
		readByLang: "/document/readByLang",
		readBySlug: "/document/readBySlug",
		readFile: "/document/readFile",
		update: "/document/update",
		create: "/document/create",
		delete: "/document/delete",
	},
	faqs: {
		read: "/faqs/read",
		readByLang: "/faqs/readByLang",
		update: "/faqs/update",
		create: "/faqs/create",
		delete: "/faqs/delete",
	},
	download: {
		read: "/download/read",
		readById: "/download/readById",
		readByLang: "/download/readByLang",
		readBySlug: "/download/readBySlug",
		update: "/download/update",
		create: "/download/create",
		preview: "/download/preview",
		download: "/download/download",
		delete: "/download/delete",
	},
	form: {
		read: "/form/read",
		readByLang: "/form/readByLang",
		update: "/form/update",
		create: "/form/create",
		delete: "/form/delete",
	},
	personalization: {
		read: "/personalization/read",
		readByLang: "/personalization/readByLang",
		update: "/personalization/update",
		create: "/personalization/create",
		delete: "/personalization/delete",
	},
};

export default endpoints;
